### ISSUE TITLE
outage calculation in upgrade looks incorrect. See

### ISSUE THREAD

**Issue by sanchezl** [openshift/cluster-kube-apiserver-operator#903]
outage calculation in upgrade looks incorrect. See

```
status:
  conditions:
  - lastTransitionTime: "2020-07-08T15:09:11Z"
    message: 'openshift-apiserver-service-172-30-151-149-443: tcp connection to 172.30.151.149:443
      succeeded'
    reason: TCPConnectSuccess
    status: "True"
    type: Reachable
  failures:
  - latency: 10.005827597s
    message: 'openshift-apiserver-service-172-30-151-149-443: failed to establish
      a TCP connection to 172.30.151.149:443: dial tcp 172.30.151.149:443: i/o timeout'
    reason: TCPConnectError
    success: false
    time: "2020-07-08T15:41:50Z"
  - latency: 10.001308826s
    message: 'openshift-apiserver-service-172-30-151-149-443: failed to establish
      a TCP connection to 172.30.151.149:443: dial tcp 172.30.151.149:443: i/o timeout'
    reason: TCPConnectError
    success: false
    time: "2020-07-08T15:41:36Z"
  - latency: 10.002833732s
    message: 'openshift-apiserver-service-172-30-151-149-443: failed to establish
      a TCP connection to 172.30.151.149:443: dial tcp 172.30.151.149:443: i/o timeout'
    reason: TCPConnectError
    success: false
    time: "2020-07-08T15:40:20Z"
  - latency: 10.000673641s
    message: 'openshift-apiserver-service-172-30-151-149-443: failed to establish
      a TCP connection to 172.30.151.149:443: dial tcp 172.30.151.149:443: i/o timeout'
    reason: TCPConnectError
    success: false
    time: "2020-07-08T15:40:17Z"
  successes:
  - latency: 1.281624ms
    message: 'openshift-apiserver-service-172-30-151-149-443: tcp connection to 172.30.151.149:443
      succeeded'
    reason: TCPConnect
    success: true
    time: "2020-07-08T15:54:16Z"
  - latency: 1.549382ms
    message: 'openshift-apiserver-service-172-30-151-149-443: tcp connection to 172.30.151.149:443
      succeeded'
    reason: TCPConnect
    success: true
    time: "2020-07-08T15:54:15Z"
  - latency: 1.819134ms
    message: 'openshift-apiserver-service-172-30-151-149-443: tcp connection to 172.30.151.149:443
      succeeded'
    reason: TCPConnect
    success: true
    time: "2020-07-08T15:54:14Z"
  - latency: 192.237µs
    message: 'openshift-apiserver-service-172-30-151-149-443: tcp connection to 172.30.151.149:443
      succeeded'
    reason: TCPConnect
    success: true
    time: "2020-07-08T15:54:13Z"
  - latency: 676.948µs
    message: 'openshift-apiserver-service-172-30-151-149-443: tcp connection to 172.30.151.149:443
      succeeded'
    reason: TCPConnect
    success: true
    time: "2020-07-08T15:54:12Z"
  - latency: 256.643µs
    message: 'openshift-apiserver-service-172-30-151-149-443: tcp connection to 172.30.151.149:443
      succeeded'
    reason: TCPConnect
    success: true
    time: "2020-07-08T15:54:11Z"
  - latency: 1.815262ms
    message: 'openshift-apiserver-service-172-30-151-149-443: tcp connection to 172.30.151.149:443
      succeeded'
    reason: TCPConnect
    success: true
    time: "2020-07-08T15:54:10Z"
  - latency: 435.609µs
    message: 'openshift-apiserver-service-172-30-151-149-443: tcp connection to 172.30.151.149:443
      succeeded'
    reason: TCPConnect
    success: true
    time: "2020-07-08T15:54:09Z"
  - latency: 1.409842ms
    message: 'openshift-apiserver-service-172-30-151-149-443: tcp connection to 172.30.151.149:443
      succeeded'
    reason: TCPConnect
    success: true
    time: "2020-07-08T15:54:08Z"
  - latency: 2.111243ms
    message: 'openshift-apiserver-service-172-30-151-149-443: tcp connection to 172.30.151.149:443
      succeeded'
    reason: TCPConnect
    success: true
    time: "2020-07-08T15:54:07Z"
```

_Originally posted by @deads2k in https://github.com/openshift/cluster-kube-apiserver-operator/pull/893#issuecomment-656790992_
